name: GitHub Action Renovatebot
description:
  GitHub Action that runs renovatebot with a very opinionated runner configuration.  It supports
  configuring it to talk to private registries for Artifactory, Docker, NPM and Terraform.
inputs:
  dry-run:
    required: false
    description: Whether to run the action in dry-run mode
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  artifactory-username:
    required: false
    description: Username to authenticate against a maven artifactory
  artifactory-password:
    required: false
    description: Password to authenticate against a maven artifactory
  artifactory-username-property-name:
    required: false
    description: Name of the gradle property to use for the artifactory username
    default: artifactoryUsername
  artifactory-password-property-name:
    required: false
    description: Name of the gradle property to use for the artifactory password
    default: artifactoryAuthToken
  artifactory-match-host:
    required: false
    description: A domain name, host name or base URL to match maven artifactory libraries with (see https://docs.renovatebot.com/configuration-options/#matchhost)
  artifactory-registry-urls:
    required: false
    description: A comma separate list of extra registry URLs to tell renovate to use to find new versions of packages (e.g a jfrog registry)
  artifactory-package-prefixes:
    required: false
    description: Package prefix to tell renovate to look for dependencies in the artifactory-registry-urls (e.g com.openTuro)
  env-regex:
    description: Override the environment variables which will be passsed into the renovate container. Defaults to `^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|(?:HTTPS?|NO)_PROXY|(?:https?|no)_proxy)$`
    required: false
  extra-config:
    required: false
    description: Extra configuration to pass to renovate. It has to be a valid JSON object. Use with caution as this could override the default configuration created by this action
    default: "{}"
  docker-username:
    required: false
    description: Username to authenticate against docker hub
  docker-password:
    required: false
    description: Password to authenticate against docker hub
  docker-volumes:
    description: |
      Docker volume mounts. Default to /tmp:/tmp
    default: /tmp:/tmp
    required: false
  github-token:
    required: true
    description: GitHub token that can checkout the repository as well as create tags/releases against it. e.g. 'secrets.GITHUB_TOKEN'
    default: ${{ github.token }}
  git-ignored-authors:
    required: false
    description: Additional Git authors which are ignored by Renovate. Must conform to RFC5322
    default: "[]"
  log-level:
    required: false
    description: Log level to use for renovate
    default: info
  npm-token:
    required: false
    description: NPM token to use for authentication
  npm-username:
    required: false
    description: Username to authenticate against the NPM registry
  npm-password:
    required: false
    description: Password to authenticate against the NPM registry
  npm-scope:
    required: false
    description: Scope of the packages to use the custom NPM authentication (e.g @open-turo)
  npm-registry:
    required: false
    description: URL of the NPM registry to use the custom authentication for
  terraform-token:
    required: false
    description: Token to authenticate against terraform registry
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      if: inputs.checkout-repo == 'true'
    - name: Renovatebot
      uses: renovatebot/github-action@v46.0.1
      env:
        LOG_LEVEL: ${{ inputs.log-level }}
        RENOVATE_ARTIFACTORY_MATCH_HOST: ${{ inputs.artifactory-match-host }}
        RENOVATE_ARTIFACTORY_PACKAGE_PREFIXES: ${{ inputs.artifactory-package-prefixes }}
        RENOVATE_ARTIFACTORY_PASSWORD: ${{ inputs.artifactory-password }}
        RENOVATE_ARTIFACTORY_PASSWORD_PROPERTY_NAME: ${{ inputs.artifactory-password-property-name }}
        RENOVATE_ARTIFACTORY_REGISTRY_URLS: ${{ inputs.artifactory-registry-urls }}
        RENOVATE_ARTIFACTORY_USERNAME: ${{ inputs.artifactory-username }}
        RENOVATE_ARTIFACTORY_USERNAME_PROPERTY_NAME: ${{ inputs.artifactory-username-property-name }}
        RENOVATE_EXTRA_CONFIG: ${{ inputs.extra-config }}
        RENOVATE_DRY_RUN: ${{ inputs.dry-run }}
        RENOVATE_DOCKERHUB_PASSWORD: ${{ inputs.docker-password }}
        RENOVATE_DOCKERHUB_USERNAME: ${{ inputs.docker-username }}
        RENOVATE_GIT_IGNORED_AUTHORS: ${{ inputs.git-ignored-authors }}
        RENOVATE_NPM_PASSWORD: ${{ inputs.npm-password }}
        RENOVATE_NPM_REGISTRY: ${{ inputs.npm-registry }}
        RENOVATE_NPM_SCOPE: ${{ inputs.npm-scope }}
        RENOVATE_NPM_AUTH_TOKEN: ${{ inputs.npm-token }}
        RENOVATE_NPM_USERNAME: ${{ inputs.npm-username }}
        RENOVATE_REPOSITORY_NAME: ${{ github.repository }}
        RENOVATE_TERRAFORM_TOKEN: ${{ inputs.terraform-token }}
      with:
        configurationFile: ${{ github.action_path }}/renovate-config.js
        docker-volumes: ${{ inputs.docker-volumes }}
        env-regex: ${{ inputs.env-regex }}
        token: ${{ inputs.github-token }}
