#!/usr/bin/env bash

set -e

for i in $*; do
  # ignore if the file does not end with /action.yaml
  if [[ "$i" != *"action.yaml" ]]; then
    echo "skipping: ${i}"
    continue
  fi
  readme_file=$(dirname "$i")/README.md
  echo "npx action-docs --no-banner -s "${i}""
  npx action-docs@2 --no-banner -s "${i}" -u "${readme_file}"
done
