name: Update dependencies
concurrency: update-dependencies

on:
  workflow_dispatch:
  issue_comment:
    types:
      - edited
  pull_request:
    types:
      - edited

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    name: Update dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./action.yaml
        with:
          github-token: ${{ secrets.OPEN_TURO_GITHUB_TOKEN }}
